### PR TITLE
Added Hyperchaotic Roessler and Lorenz systems

### PR DESCRIPTION
**Pull request by MartinuzziFrancesco**
Starting the hyperchaotic systems additions with the extensions of the two classics

### CODE REVIEW

**Comment by Datseris** [comment]
Sounds good but please replace the `CDS` with `CoupledODEs`!

**Comment by MartinuzziFrancesco** [comment]
Uh I see! Should I apply that change to the other systems as well?

**Comment by Datseris** [comment]
no we should do this in a different Pr for clarity

**Comment by MartinuzziFrancesco** [comment]
gotcha, changed for the two systems in this pr. Will open a second as soon as this is merged with the changes for the other systems

**Pull request merged**
